// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvPKSl12xT0CWmALgm63Yc3YV_AImTH7s',
    appId: '1:1098874852025:android:85af986aff1842e70e8168',
    messagingSenderId: '1098874852025',
    projectId: 'bing-daily',
    storageBucket: 'bing-daily.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiwx1x4hUKcRb5HE2u0-0-BxxUcrQ1jAw',
    appId: '1:1098874852025:ios:2ec1a8e7f9b3abb10e8168',
    messagingSenderId: '1098874852025',
    projectId: 'bing-daily',
    storageBucket: 'bing-daily.firebasestorage.app',
    androidClientId: '1098874852025-9cm4o3taotgntmu3gcokdkm8mknatulk.apps.googleusercontent.com',
    iosClientId: '1098874852025-rkudo82gnti4un9764gq1h59uugasiop.apps.googleusercontent.com',
    iosBundleId: 'com.example.bingDaily',
  );

}